Fixes #1277
USGS-WiM/StreamStats pull request #1345
Opened 2022-06-22 15:31 UTC by harper-wavra

Added Urban Bohman method.
Added some code to start work on Rural Bohman Method and Synthetic Urban Hydrograph Method.

Some testing points:
Only Region 3
33.47655626699917, -81.9091272354126
Only Region 4
33.05054, -80.85092
Both Region 3 & 4
33.87821873743382, -80.68458080291748

2022-06-24 13:59 UTC, amedenblik requested changes
Looks awesome!! 🤩

I've added some code comments. Please let me know if you'd like help! We can break into separate issues too.

- [ ] Please update the Changelog

2022-06-24 13:59 UTC, amedenblik commented on dist/Views/scstormrunoff.html
> +                                                    <th>Time</th>
Add units: "Time (hours)"

2022-06-24 13:59 UTC, amedenblik commented on dist/Views/scstormrunoff.html
> +                                                    <th>Q</th>
Add units: "Q (cubic feet per second)"

2022-06-24 13:59 UTC, amedenblik commented on dist/Views/scstormrunoff.html
> +                                                    <td>Weighted Runoff Volume:</td>
Add units: "Weighted Runoff Volume (inches):"

2022-06-24 13:59 UTC, amedenblik commented on dist/Views/scstormrunoff.html
> +                                                    <td>{{vm.reportData.discharge_coordinates[$index]}}</td>
Reduce the number of decimal places to 1 for the Q values. Then we won't have values like 296.09999999999997 (should be 296.1)

2022-06-24 13:59 UTC, amedenblik commented on dist/Views/scstormrunoff.html
> +                                                <tr ng-repeat="item in vm.reportData.time_coordinates">
Reduce the number of decimal places to 5 for the Time values (we may need to adjust this again later based on feedback from Kitty and cooperator).

2022-06-24 13:59 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                    <td><b>{{vm.ReportData.BohmanUrban1992.WeightedRunoff}}</b></td>
Reduce the number of decimal places to 5 for the Weighted Runoff Volume (we may need to adjust this again later based on feedback from Kitty and cooperator)

2022-06-24 13:59 UTC, amedenblik commented on src/Controllers/SCStormRunoffController.ts
> +            this.ReportOptions = {
- [x] Change x-axis label formatting so that the Time values are just whole numbers instead of having many decimal places
![image](https://user-images.githubusercontent.com/40237491/175548760-f379fa33-c81c-484c-a951-721dfbd5bc08.png)

- [x] Add x-axis label: "Time, in hours"
- [x] Add y-axis label: (see Colorado example)
![image](https://user-images.githubusercontent.com/40237491/175548514-dc14819b-e4fb-4025-8f50-f6b67d399365.png)

2022-06-24 13:59 UTC, amedenblik commented on dist/Views/scstormrunoff.html
> +            <div class="btn-group">
- [ ] Add option to "Download CSV"
- [ ] Add option to "Print" report

2022-06-24 13:59 UTC, amedenblik commented on dist/Views/scstormrunoff.html
> +
Add disclaimers (see Colorado report example)
![image](https://user-images.githubusercontent.com/40237491/175549817-1d6fa956-d658-4f8b-80e3-ad755752f1ff.png)

2022-06-24 13:59 UTC, amedenblik commented on dist/Views/scstormrunoff.html
> +                            </div>
Add citation (see Colorado report for example):

Bohman, L.R., 1992, Determination of flood hydrographs for streams in South Carolina: Volume 2. Estimation of peak-discharge frequency, runoff volumes, and flood hydrographs for urban watersheds: U.S. Geological Survey Water-Resources Investigations Report 92-4040, 79 p.

URL: https://doi.org/10.3133/wri924040

2022-06-24 13:59 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +
Add gray bar near the top (see Colorado example): 
![image](https://user-images.githubusercontent.com/40237491/175551088-af9a77d7-c181-476e-b25c-466dc357de6f.png)

2022-06-24 15:55 UTC, harper-wavra commented on dist/Views/scstormrunoff.html
> +            <div class="btn-group">
Added issue https://github.com/USGS-WiM/StreamStats/issues/1346

2022-06-27 19:32 UTC, amedenblik approved these changes
Changes look good. Created #1347 to handle some outstanding issues.

2022-06-27 19:32 UTC, merged