Fixes #1363
USGS-WiM/StreamStats pull request #1364
Opened 2022-07-12 13:06 UTC by harper-wavra

2022-07-12 14:32 UTC, amedenblik requested changes
Seems to work well!

2022-07-12 14:32 UTC, amedenblik commented on CHANGELOG.md
> +  - Changed Coordinated Reach to new layer, [https://services.arcgis.com/2Mcx1M1MORKfBNPM/arcgis/rest/services/Indiana_Coordinated_Discharge_view/FeatureServer](https://gcc02.safelinks.protection.out
Change the hyperlink, since it's currently an Outlook protection link

2022-07-12 14:32 UTC, amedenblik commented on src/Services/StudyAreaService.ts
> +                var url = 'https://services.arcgis.com/2Mcx1M1MORKfBNPM/' + configuration.queryparams['coordinatedReachQueryService']
I would change the "coordinatedReachQueryService" link in the appConfig to be "https://services.arcgis.com/2Mcx1M1MORKfBNPM/ArcGIS/rest/services/Indiana_Coordinated_Discharge_view/FeatureServer/2/query?geometry={0},{1},{2},{3}&geometryType=esriGeometryEnvelope&inSR={4}&spatialRel=esriSpatialRelIntersects&outFields={5}&returnGeometry=false&returnIdsOnly=false&returnCountOnly=false&returnZ=false&returnM=false&f=pjson" and then change this line to be: `var url = + configuration.queryparams['coordinatedReachQueryService']`

2022-07-12 14:32 UTC, amedenblik commented on src/appConfig.js
> +        'coordinatedReachQueryService': 'ArcGIS/rest/services/Indiana_Coordinated_Discharge_view/FeatureServer/2/query?geometry={0},{1},{2},{3}&geometryType=esriGeometryEnvelope&inSR={4}&spatialRel=e
I would change this line to: `'coordinatedReachQueryService': 'https://services.arcgis.com/2Mcx1M1MORKfBNPM/ArcGIS/rest/services/Indiana_Coordinated_Discharge_view/FeatureServer/2/query?geometry={0},{1},{2},{3}&geometryType=esriGeometryEnvelope&inSR={4}&spatialRel=esriSpatialRelIntersects&outFields={5}&returnGeometry=false&returnIdsOnly=false&returnCountOnly=false&returnZ=false&returnM=false&f=pjson',`

2022-07-12 14:32 UTC, amedenblik commented on dist/appConfig.js
>                  "layerOptions": {
Is it possible to change the color of the layer here? It is currently blue, making it hard to see compared to the streams. We may also be able to ask Indiana DNR to change the symbiology in their published layer. 

![image](https://user-images.githubusercontent.com/40237491/178514386-49be9863-0043-40a8-bb46-555124667d28.png)

2022-07-12 14:34 UTC, harper-wavra commented on dist/appConfig.js
>                  "layerOptions": {
I can look into it, but when we were trying to change the symbiology o the old layer we ended up just changing it in the map service.

2022-07-12 14:37 UTC, amedenblik commented on dist/appConfig.js
>                  "layerOptions": {
Yeah let's just ask Indiana DNR if it's possible for them to change it.

2022-07-15 17:08 UTC, harper-wavra commented
Closing until we have more information from IN.

2022-07-15 17:08 UTC, closed without merging