CS-1386: SC Synthetic UH: Compute output data
USGS-WiM/StreamStats pull request #1408
Opened 2022-08-16 15:45 UTC by KipSullivan

There are still likely many UI things that need to change (titles of the tables, alignment, etc), but this is the first proof-of-concept for adding visual data for the results computed by the 'scsyntheticunithydrograph' endpoint. Let me know what needs to be changed/added in.

- Added tables and hydrograph for Watershed Data, Unit Hydrograph Data, Runoff Results, and Storm Hydrograph Ordinates

Things of note/might need to be changed/improved:
- I pulled from branch origin 'SC-Runoff' to make sure this branch was up-to-date, and the 'State/Region Specific Functions' sidebar now has one less option to choose from. I'm guessing this is a new intentional thing, this is just the first I've seen it so I thought I would mention it
<img width="363" alt="sideview" src="https://user-images.githubusercontent.com/76274215/184921257-c9ac4bd7-c56d-450e-9b26-eac94fa09247.PNG">

- When the 'max_peak_runoff' and 'max_runoff_value' values are the same, the table row that is supposed to be highlighted is the color blue. The idea is that these two values would be different, so that for 'max_peak_runoff' the row would be red, and for 'max_runoff_value' it would be blue, but when they're the same, I'm not sure what to do. Let me know if you want that to be a different color when the two values are the same.
<img width="893" alt="firstandlast" src="https://user-images.githubusercontent.com/76274215/184921762-b5f19aa7-b502-4514-b3dd-c20b3e32a803.PNG">

- The title for the Hydrograph is simply "Hydrograph", pretty non-descript. Also, let me know if the axis should be labeled differently, I just went off of this image (the second one here)
<img width="892" alt="titleandtimeinminutes" src="https://user-images.githubusercontent.com/76274215/184921842-07a6d856-d809-48af-add9-ebd8306ef986.PNG">
![hydrograph](https://user-images.githubusercontent.com/76274215/184922092-8f8d7ac8-a057-4014-9230-9edf694729a1.png)

2022-08-16 15:45 UTC, KipSullivan commented
Need to change conflicts, will do that quickly

2022-08-16 18:44 UTC, amedenblik requested changes
![image](https://user-images.githubusercontent.com/40237491/184955180-32220bb5-d1cb-4a1f-9ca9-cc5bd54cea0a.png)

Nice work 👌 Please see review comments!

2022-08-16 18:44 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                    <p class="fullwidth alignc hidden-print" style="font-size: 16px;"><b>USGS SC Flood Hydrograph for Synthetic Units using {{vm.SelectedAEPSynthetic.name}} AEP</b></p
Right now this says "USGS SC Flood Hydrograph for Synthetic Units using 10% / 10 Year Return Period AEP", but it should say "USGS SC Flood Hydrograph for Synthetic Units using 10% AEP / 10 Year Return Period". Feel free to change the drop-down values for the AEP selector to be "10% AEP / 10 Year Return Period", etc.

2022-08-16 18:44 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                        <a href="https://www.scdot.org/business/technicalPDFs/hydraulic/SPR-738-SC-UH-Method-Application-Manual-May-2020.pdf" target="_blank">Meadows, M.E., 2020, Sout
Apologies, can you please change the URL to https://www.scdot.org/business/hydraulic-calculations.aspx ?

2022-08-16 18:44 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                    <td><b>{{vm.syntheticResponseData.unit_hydrograph_data["Burst Duration"]}} minutes</b></td>
Don't need to put " minutes" in the second column, since it's in the first column

2022-08-16 18:44 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                    <td><b>{{vm.studyAreaService.selectedStudyArea.Pourpoint.Latitude.toUSGSvalue()}}, {{vm.studyAreaService.selectedStudyArea.Pourpoint.Longitude.toUS
We don't want to use `.toUSGSvalue()` on Latitude and Longitude

2022-08-16 18:44 UTC, amedenblik commented on src/Controllers/SCStormRunoffController.js
> +                results.push({ values: hydrograph, key: "Flow (cfs)", color: " #009900", type: "line", yAxis: 1 });
Change to "Flow (ft³/s)"

2022-08-16 18:44 UTC, amedenblik commented on src/Controllers/SCStormRunoffController.ts
> +            results.push({ values: hydrograph, key: "Flow (cfs)", color: " #009900", type: "line", yAxis: 1 });
Change to "Flow (ft³/s)"

2022-08-16 18:44 UTC, amedenblik commented on src/Controllers/SCStormRunoffController.js
> +                            axisLabel: 'Flow, cfs',
Change to "Flow, in ft³/s"

2022-08-16 18:44 UTC, amedenblik commented on src/Controllers/SCStormRunoffController.ts
> +                        axisLabel: 'Flow, cfs',
Change to "Flow, in ft³/s"

2022-08-16 18:44 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                    <th>CN Adjusted for Rainfall Duration {{"<"}} 24-hr &ensp;</th>
Remove space between "<" and "24-hr" so they appear on the same line

2022-08-16 18:44 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                    <th>Runoff Volume Qcn (WS-in) &ensp;</th>
See if you can put the "CN" as a subscript of the "Q"

2022-08-16 18:44 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                    <th>Peak Runoff, Qp (cfs) &ensp;</th>
See if you can put the "p" as a subscript of the "Q"

2022-08-16 18:44 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                <accordion-heading><i ng-class="vm.stormHydrographOrdinatesAccordionOpen ? 'fa fa-chevron-down': 'fa fa-chevron-right'"></i> Storm Hydrograph Ordinates
Rename to "D-Hour Storm Hydrograph Ordinates"

2022-08-16 18:44 UTC, amedenblik commented on src/css/main.css
> +.max-runoff-volume {
Thanks for bringing our attention to the fact that sometimes the maximum peak runoff and maximum peak runoff could be the same value, which causes some complexity. For the sake of simplicity, let's scrap the table highlighting. Below the "Runoff Results" table, please add a table called "Critical Durations": (fake values here)

| Maximum Runoff Value | Storm Duration (hrs) |
| ------------------------- | --------------------- | 
| Maximum Runoff Volume | 12 | 
| Maximum Peak Runoff | 3 |

2022-08-16 19:28 UTC, harper-wavra requested changes
This looks great! We did remove the Hydrologic Features options from the sidebar and moved it lower in the workflow. 

I wonder if you could get D-Storm Hour: and the drop down to show up on the same line?
![image](https://user-images.githubusercontent.com/59063181/184962858-8c5a559e-48fc-4492-9124-a9f552bc7ba7.png)

2022-08-16 19:28 UTC, harper-wavra commented on dist/Views/sidebarview.html
> +                                <button ng-show="vm.regionService.selectedRegion.Applications.indexOf('HydrologicFeatures') != -1" ng-click="vm.OpenSelectHydrologicFeatures()" type="button" class="bt
After you finish making changes I think you should try to rebuild the application so we don't get this old dist file pulled back into the branch. The instructions are in the readme, https://github.com/USGS-WiM/StreamStats#building-and-testing, you should just have to run `npm run-script build`. 

I guess I am not sure if you ever got approved for a pr account but I think that command might need to be run from an admin command prompt. If you try and it doesn't work Andrea or I can rebuild this branch before we merge.

2022-08-17 16:35 UTC, KipSullivan commented
New commit:
- Added subscripts, title changes, and fixed other requests where mentioned
- New link for the Citation on the bottom of the page
- Re-built application to hopefully solve old dist file issues
- Made "D-Hour Storm" label and its drop down on the same line
![centeredlabel](https://user-images.githubusercontent.com/76274215/185194299-a2ccd267-3894-40a6-aef2-6765e3a05235.PNG)

- Added "Critical Durations" table to replace previously highlighted Runoff table rows
![criticaldurations](https://user-images.githubusercontent.com/76274215/185194407-90cca943-a2ee-4079-aa91-ad79f075fb34.PNG)


Let me know if I missed anything/any more requests to be added for this branch!

2022-08-18 22:38 UTC, amedenblik requested changes
Changes look great! 2 tiny changes:

- [ ] My apologies, I messed up-- can you apply `.toFixed(5)` to the Latitude and Longitude values in the table? 
- [ ] Please change the y-axis label to be "Flow, ft³/s," instead of "Flow, cfs"
- [ ] And then don't forget to rebuild again after making the changes (I frequently forget..)

2022-08-19 14:31 UTC, KipSullivan commented
- Applied .toFixed(5) to the Lat and Long values for the Watershed Data table
- Fixed y-axis label for hydrograph
- Rebuilt project using 'npm run-script build' - I did this for the last commit as well, if it's not working as intended let me know and I'll look into it

2022-08-19 17:25 UTC, harper-wavra approved these changes
This looks great! I am good to approve. 

Yes it looks like when you build it updated the correct files.

2022-08-22 14:40 UTC, amedenblik approved these changes

2022-08-22 14:40 UTC, merged

2022-08-22 14:41 UTC, amedenblik commented
Deployed changes to https://dev.streamstats.usgs.gov/sc-runoff/