Fixes #1392
USGS-WiM/StreamStats pull request #1433
Opened 2022-09-27 15:20 UTC by harper-wavra

- Added notes to bottom of SC Unit Hydrograph results
- Fixed bug when downloading csv and D-Hour results are not open

2022-09-28 20:03 UTC, amedenblik requested changes
Works well! I would recommend making each of the notes an item <li> in an ordered list <ol> for formatting purposes. I would also make the text smaller, since it is currently larger than the header ("Notes on Time of Concentration:").

2022-09-29 13:18 UTC, harper-wavra commented
I was able to edit the text size a bit, let me know if that is better. 
I tried making them a list originally but the output to the csv was being very finicky with it as was the style of the modal once I added the `<ul>` and `<li>` tags.

2022-09-29 14:09 UTC, amedenblik requested changes
Ah, I hadn't considered the difficulty with the <ol> and the CSV formatting! It is looking better. Do you think you can add a little space between the points? Maybe 2 <br> instead of 1?

2022-10-04 16:56 UTC, amedenblik approved these changes

2022-10-04 16:56 UTC, merged