Fixes #1500
USGS-WiM/StreamStats pull request #1501
Opened 2023-01-10 21:02 UTC by harper-wavra

Should be working on https://dev.streamstats.usgs.gov/gageplots/

- Added highcharts - see https://stackoverflow.com/questions/41244791/cannot-read-property-chart-of-undefined-highcharts-ng
- Gave default values to plotLines to remove errors inline code errors
- Was seeing errors with `this.formattedPeakDates.length > 0` & `this.formattedEstPeakDates.length > 0` when `formattedPeakDates` or `formattedEstPeakDates` where not defined. I change those two lines of code to match `showInLegend: this.formattedDailyFlow != undefined`.

2023-01-10 22:06 UTC, maggiejaenicke requested changes
Looks great! I'm glad you got the chart to load!

The only other thing I noticed was that charts with no data no longer have the 'No data to display message'. Instead, it's an empty plot. I'm not sure if that happened in these changes or earlier, maybe something we should revisit. 

<img width="546" alt="empty_plot" src="https://user-images.githubusercontent.com/91270407/211670492-580d5f74-fea2-43b8-b1e6-2cfd260c84fe.PNG">

2023-01-10 22:06 UTC, maggiejaenicke commented on src/Controllers/GagePageController.js
> +                console.log(this.chartConfig);
Will we need to clear out/comment console logs? Feel free to ignore this if not, but that was something brought up in my original PR.

2023-01-10 22:06 UTC, maggiejaenicke commented on src/Controllers/GagePageController.ts
> +                    showInLegend: this.formattedEstPeakDates != undefined
With this change I'm now seeing that Estimated Peak Streamflow is showing up in the legend but have no data points (ex: 02173351) on sites that **do have** regular peak values. The showInLegend line is working correctly at sites that have **neither** peak streamflow values or estimated peak streamflow values (ex: 02156450). 

This seems to be happening because when there is normal peak date data (but no invalid dates), it results in an array with a length of 0 for the estimated peaks (not undefined), so it shows in the legend. When there is no normal peak date data present, both the Peak Dates and Estimated Peak dates are undefined, which is what is currently working. 

I'm not sure the best solution here, since neither _.length >0_ or _!= undefined_ will cover both scenarios, but maybe there's another way to write this that will handle both. 

I think _!= undefined_ works well for the other two series.

2023-01-10 23:29 UTC, amedenblik requested changes

2023-01-10 23:29 UTC, amedenblik commented on src/Controllers/GagePageController.js
> +                console.log(this.chartConfig);
```suggestion
```

2023-01-10 23:29 UTC, amedenblik commented on src/Controllers/GagePageController.ts
> +                    showInLegend: this.formattedEstPeakDates != undefined
To fix this, I recommend changing this (lines 676-681):
```
            if (this.estPeakDates) {
                this.formattedEstPeakDates = [];
                this.estPeakDates.forEach(estPeakObj => {
                    this.formattedEstPeakDates.push({x: new Date(estPeakObj.peak_dt), y: estPeakObj.peak_va})
                });
            }
```

to this:

```
            if (this.estPeakDates) {
                this.estPeakDates.forEach(estPeakObj => {
                    if (!this.formattedEstPeakDates) {
                        this.formattedEstPeakDates = [];
                    }
                    this.formattedEstPeakDates.push({x: new Date(estPeakObj.peak_dt), y: estPeakObj.peak_va})
                });
            }
```

2023-01-11 14:00 UTC, harper-wavra commented on src/Controllers/GagePageController.ts
> +                    showInLegend: this.formattedEstPeakDates != undefined
It doesn't go into that loop unless there is `estPeakDates`, which in the case of [06342500] there isn't. I'll look into it more.

2023-01-11 14:21 UTC, harper-wavra commented
I think I got it working, I just initialized all the formatted arrays at the beginning and then to set the legend I am always looking for length greater than one. I tested a few sites and things seemed to be working but let me know if you find any that are not.

2023-01-11 14:50 UTC, amedenblik approved these changes

2023-01-11 15:40 UTC, maggiejaenicke approved these changes
Looks good!

2023-01-11 15:41 UTC, merged

2023-01-11 15:41 UTC, harper-wavra commented
I can update the dev site.

2023-01-11 21:31 UTC, harper-wavra commented
The dev site is now updated.