Fixes #1498 Additional Functionality for Annual Flow Plot with Flood-Frequency Statistics
USGS-WiM/StreamStats pull request #1515
Opened 2023-01-26 19:56 UTC by maggiejaenicke

Let me know what you think about having all in data in the navigator (timeline slider). That was the only way I could make sure all data were shown on initial load. 

Closes #1498.

2023-01-27 00:04 UTC, amedenblik requested changes
- [ ] Unrelated to this issue: for gage 02169630 I'm seeing "Annual Peak Streamflow (Date Estimated)" in the legend, but I'm not seeing red dots on the plot: 
![image](https://user-images.githubusercontent.com/40237491/214977337-8b8cdeab-fbf2-47ee-a9f2-e256c5de80b4.png)

- [ ] The Annual Peak Streamflow values are appearing in the navigator as a black line, rather than black dots. Is there a way to change this to dots? The line is a little misleading/distracting.
![image](https://user-images.githubusercontent.com/40237491/214977402-0e37bd3e-c6cc-422e-b500-52efb6d994bf.png)

If the goal is to try to show the full extent of all data from the beginning, an alternative way to do this might be: figure out what is the earliest date among all the available data (Daily Streamflow, Annual Peak Streamflow, and Annual Peak Streamflow (Date Estimated)). Then set that to the min x-axis value. I think that would work?

2023-01-27 00:04 UTC, amedenblik commented on src/Controllers/GagePageController.ts
> +            public removePlotLines () {
Consider renaming this function to `togglePlotLines`, since it doesn't just remove the lines.

2023-01-27 00:04 UTC, amedenblik commented on src/index.html
> +    <!-- <script src="http://code.highcharts.com/stock/highstock.src.js"></script> -->
Removed lines that are commented out

2023-01-27 00:04 UTC, amedenblik commented on src/Controllers/GagePageController.ts
> +        public logToLinear () {
Consider renaming this function to something like `toggleLogLinear`, since it doesn't just change it from to log to linear

2023-01-27 00:04 UTC, amedenblik commented on src/Controllers/GagePageController.ts
> +        public removeAEPLines: boolean;
Can this variable be removed? I don't think it's used elsewhere.

2023-01-27 14:40 UTC, harper-wavra requested changes
These changes are looking good!

- I don't think I am seeing the AEP lines on some plots. For example, 06471200 has a couple AEP flood statistics but I am not seeing those lines.

2023-01-31 15:41 UTC, maggiejaenicke commented
Thanks for both of your comments--I believe I fixed everything. To Harper's comment about seeing not seeing AEP lines on 06471200, I looked through the data and it looks like all the regressionTypeIDs we're looking for are marked "false" on isPreffered. If I'm missing something--happy to make changes to that!

2023-02-01 14:08 UTC, harper-wavra approved these changes
I think this is looking good! It will be nice to get this on the test stie so Pete and the SC cooperators can see.

2023-02-02 18:18 UTC, amedenblik approved these changes
Looks good! I can rebuild and update on https://dev.streamstats.usgs.gov/gageplots/

2023-02-02 18:21 UTC, merged