Fixes #1499 - Daily Value Raster Plot
USGS-WiM/StreamStats pull request #1558
Opened 2023-02-23 22:57 UTC by maggiejaenicke

**Logarithmic test sites:** 02173500, 1234000
**Linear test sites:** 02324500, 02231291, most places in Florida
Closes #1499.

2023-02-24 14:58 UTC, harper-wavra requested changes
These plots are so pretty!

It does kind of freeze up for a second right after you select the 'Gage Analysis Plot' tab. I wonder if we could add some kind of loader. I think we have some loaders in the gagepage.html already so if we could get it to switch tabs right when you click that could solve it. If that isn't working, maybe we could add a full-page loader or perhaps a spinner next to the text on the 'Gage Analysis Plots' tab, just something to show the user that it is thinking. - feel free to break that into a different issue.

2023-02-24 14:58 UTC, harper-wavra commented on src/Controllers/GagePageController.ts
> +            if (this.dailyFlow) {
This if statement and the if statement at 696 are the same, so they could be combined into one. If we are keeping them apart for organization purposes, maybe we could add a comment by each if statement what (or what plot) it is being used for.

2023-03-01 14:23 UTC, amedenblik requested changes
Looks great! Nice work. I left a few comments.

2023-03-01 14:23 UTC, amedenblik commented on src/Controllers/GagePageController.ts
> +                        text: 'Date'
```suggestion
                        text: 'Day of Year'
```

2023-03-01 14:23 UTC, amedenblik commented on src/Controllers/GagePageController.js
> +                                            return '</b><br>Water Year Average Value: <b>' + this.value.toFixed(2) + ' ft³/s</b><br>Water Year: <b>' + waterYear;
```suggestion
                                            return '</b><br>Water Year: <b>' + waterYear<br>Water Year Average Value: <b>' + this.value.toFixed(2) + ' ft³/s</b>;
```
Suggestion to put Water Year above the Water Year Average Value

2023-03-01 14:23 UTC, amedenblik commented on src/Controllers/GagePageController.ts
> +            this.heatChartConfig = {
Is it possible to add a label to the legend that says "Flow (ft^3/s)"?

2023-03-01 14:23 UTC, amedenblik commented on src/Views/gagepage.html
> +                        </div>
```suggestion

```

2023-03-02 20:46 UTC, amedenblik requested changes

2023-03-02 20:46 UTC, amedenblik commented on src/Controllers/GagePageController.js
> +                                            return '</b><br>Water Year Average Value: <b>' + this.value.toFixed(2) + ' ft³/s</b><br>Water Year: <b>' + waterYear;
I am still seeing Water Year Average Value above Water Year
![image](https://user-images.githubusercontent.com/40237491/222547548-9d618e93-7220-47ba-9ef8-8bac69723193.png)

2023-03-02 20:56 UTC, maggiejaenicke commented on src/Controllers/GagePageController.js
> +                                            return '</b><br>Water Year Average Value: <b>' + this.value.toFixed(2) + ' ft³/s</b><br>Water Year: <b>' + waterYear;
Whoops I thought that one would automatically fix with the GitHub commit suggestion button. Just fixed it locally!

2023-03-02 21:16 UTC, amedenblik approved these changes

2023-03-02 21:16 UTC, merged

2023-03-03 17:50 UTC, amedenblik commented
Update gageplots dev site: https://dev.streamstats.usgs.gov/gageplots/