Fixes #1559, Fixes #1565, Fixes #1566
USGS-WiM/StreamStats pull request #1577
Opened 2023-03-14 14:33 UTC by harper-wavra

- Added storm pond calcualtions
- Added USLE and MUSLE calculations
- Added storm pond sediment calculations

- We might need to talk with someone to figure out exactly what values are allowed in each input box. For example which ones can be 0 or which ones need to be greater than 0, ect.

- Need to update appconfig and use HW-105 branch & https://code.usgs.gov/StreamStats/web-services-and-apis/SC-RunoffModelingServices/-/merge_requests/107.

2023-03-22 15:23 UTC, amedenblik requested changes

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                    <button style="line-height:unset;" class="btn-wim-sm btn-wim-success btn-wim-group-1 btn-blue" ng-if="!vm.usle" ng-click="vm.usle = !vm.usle">Calculate USLE & MUSL
These 2 new buttons ("Calculate USLE & MUSLE" and "Design Storm Ponds" look the same as the other buttons, which may imply that they are "submit"-type buttons rather than a button that will toggle a new part of the form. I wonder if there is a way to make them look different to signify that they are different? Maybe a different color (black?) or making it a collapsible section? It's fine as-is, but I welcome changes if you think it would help.

![image](https://user-images.githubusercontent.com/40237491/226924802-078d564e-2163-40cd-a289-b9f7e60c2557.png)

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                        <label for="countyName">County Name<span style="color: #ffcc00">*</span></label>
```suggestion
                                        <label for="countyName">County Name:<span style="color: #ffcc00">*</span></label>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                        <label for="soilName">Soil Name<span style="color: #ffcc00">*</span></label>
```suggestion
                                        <label for="soilName">Soil Name:<span style="color: #ffcc00">*</span></label>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                        <label for="slopeLength">Slope Length<span style="color: #ffcc00">*</span></label>
```suggestion
                                        <label for="slopeLength">Slope Length (feet): (value should be less than 1000 feet)<span style="color: #ffcc00">*</span></label>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                        <label for="slopeSteepness">Slope Steepness (value should be less than 25%)<span style="color: #ffcc00">*</span></label>
```suggestion
                                        <label for="slopeSteepness">Slope Steepness (%): (value should be less than 25%)<span style="color: #ffcc00">*</span></label>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                        <label for="coverName">Cover Name<span style="color: #ffcc00">*</span></label>
```suggestion
                                        <label for="coverName">Cover Name:<span style="color: #ffcc00">*</span></label>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                        <label for="practiceName">Practice Name<span style="color: #ffcc00">*</span></label>
```suggestion
                                        <label for="practiceName">Practice Name:<span style="color: #ffcc00">*</span></label>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                    <div ng-if="vm.usle">
Can we create a little more space between the USLE & MUSLE section and the previous sections? Or make the spacing consistent between sections? Compare the space between Time of Concentration and USLE & MUSLE with the space between Time of Concentration and the above section

![image](https://user-images.githubusercontent.com/40237491/226927836-d1435343-e40b-4786-93b5-68098d71ebce.png)

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                        <h3 class="center-div">USLE & MUSLE</h3>
```suggestion
                                        <h3 class="center-div">USLE & MUSLE</h3>
                                        
                                        <div class="wim-alert hidden-print">Enter a a 'County Name', 'Soil Name', 'Slope Length', 'Slope Steepness', 'Cover Name', and 'Practice Name' to compute the R, K, LS, C, and P factors. These factors will be used to compute results related to the Universal Soil Loss Equation (USLE) and Modified Universal Soil Loss Equation (MUSLE).</div>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                            <table id="USLEDataTable" class="table table-condensed smalltext">
I would organize the tables into these:

1. Input Data
![image](https://user-images.githubusercontent.com/40237491/226934085-8f049145-7afd-4b54-b035-7fc6cb062c01.png)

2. Factors
![image](https://user-images.githubusercontent.com/40237491/226934178-94b44ceb-57e5-4d6a-9bb6-43ec21363c39.png)

3. USLE Results
Predicted Soil Loss and Gross Erosion 

4. MUSLE Results: Erosion for Single Event D-Hour Storms 
![image](https://user-images.githubusercontent.com/40237491/226934482-62f1d3ad-8ff2-4448-b1e0-26441b6341a5.png)

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                            <table id="USLEDataTable" class="table table-condensed smalltext">
Use similar rounding to what is seen in the worksheet: 

![image](https://user-images.githubusercontent.com/40237491/226930476-d36df9da-31e8-4ad4-96a6-b37cb0ec272f.png)

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                        <td>Gross Erosion</td>
```suggestion
                                                        <td>Gross Erosion (tons/year)</td>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                        <td>Predicted Soil Loss</td>
```suggestion
                                                        <td>Predicted Soil Loss (tons/acre/year)</td>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                        <div class="wim-alert hidden-print">Select a 'Pond Option' and fill out all required fields.</div>
```suggestion
                                        <div class="wim-alert hidden-print">Select a 'Pond Option' and fill out all required fields to compute pond stage-storage and stage-outflow ratings.</div>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                            <label>Inverted Quadrilateral Frustum</label>
Since the length, W1, W2, side slope, and bottom slope all seem to relate to the Inverted Quadrilateral Frustum, I would organize it like this:
![image](https://user-images.githubusercontent.com/40237491/226937226-af1654f9-0c22-4194-9853-aca4e3483454.png)

I _think_ this is what the Excel sheet is saying.

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                <label>1st Stage Circular Orifices</label>
I would add a header for this section called "Outflow Devices"

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                            <label for="bottom_slope">Bottom Slope S<sub>O</sub> (%):<span style="color: #ffcc00">*</span></label><span ng-if="SyntheticUrbanHydrograph.bottom_slope.$e
```suggestion
                                            <label for="bottom_slope">Bottom Slope S<sub>o</sub> (%):<span style="color: #ffcc00">*</span></label><span ng-if="SyntheticUrbanHydrograph.bottom_slope.$error.pattern" class="red label"><span class="fa fa-exclamation-triangle"></span>&nbsp;Value must be greater than 0</span>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                    <label>Elevation (ft-MSL) (values should be between {{vm.pond_bottom_elev}} and {{vm.pond_bottom_elev + 10}})<span style="color: #ffcc00">*</span><
```suggestion
                                                    <label>Elevation (ft-MSL): (values should be between {{vm.pond_bottom_elev}} and {{vm.pond_bottom_elev + 10}})<span style="color: #ffcc00">*</span></label>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                    <label for = "elevation">Surface Area (square feet)<span style="color: #ffcc00">*</span></label>
```suggestion
                                                    <label for = "elevation">Surface Area (square feet):<span style="color: #ffcc00">*</span></label>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                    <input type="number" value="{{vm.pond_bottom_elev}}" ng-model="vm.Elev_Area[0][0]" readonly/>
Is there a way to signify that this input field is disabled? Maybe add a `disabled` attribute? So the user knows this one is different and not editable.

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                        <input type="number" name="max_depth" ng-model="vm.max_depth" readonly/>
Is there a way to signify that this input field is disabled? Maybe add a disabled attribute? So the user knows this one is not editable.

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                    <th ng-if="vm.stormPondsResponseData">Pond Peak Inflow</th>
```suggestion
                                                    <th ng-if="vm.stormPondsResponseData">Pond Peak Inflow (cfs)</th>
```

2023-03-22 15:23 UTC, amedenblik commented on src/Views/scstormrunoff.html
> +                                                    <th ng-if="vm.stormPondsResponseData">Pond Peak Outflow</th>
```suggestion
                                                    <th ng-if="vm.stormPondsResponseData">Pond Peak Outflow (cfs)</th>
```

2023-03-22 15:23 UTC, amedenblik commented on dist/appConfig.js
- [ ] This is from a previous PR but there is a typo "Strom"
![image](https://user-images.githubusercontent.com/40237491/226952415-e8b11329-4695-4250-b41f-7bae912a9b10.png)

- [ ] I see a hydrograph with the storm pond inflow/outflow but it seems that now the normal hydrograph is missing. I think we should have 2 graphs is design storm ponds are computed.

2023-03-22 15:24 UTC, amedenblik commented
- [x] This is from a previous PR but there is a typo "Strom"
![image](https://user-images.githubusercontent.com/40237491/226952415-e8b11329-4695-4250-b41f-7bae912a9b10.png)

- [ ] I see a hydrograph with the storm pond inflow/outflow but it seems that now the normal hydrograph is missing. I think we should have 2 graphs is design storm ponds are computed.

2023-03-22 17:04 UTC, harper-wavra commented
When finished will need to 
- [ ] update services on server
- [ ] rebuild client code
- [ ] push client code to dev site

2023-03-22 18:45 UTC, harper-wavra commented on src/Views/scstormrunoff.html
> +                                    <button style="line-height:unset;" class="btn-wim-sm btn-wim-success btn-wim-group-1 btn-blue" ng-if="!vm.usle" ng-click="vm.usle = !vm.usle">Calculate USLE & MUSL
I made them black for now, but we can change once we get feedback.

2023-03-23 13:55 UTC, harper-wavra commented on src/Views/scstormrunoff.html
> +                                            <table id="USLEDataTable" class="table table-condensed smalltext">
Will create new issue for this with questions to the cooperators.

2023-03-23 14:14 UTC, harper-wavra commented
Related to the comments about the results tables, I have created a new issue here: https://github.com/USGS-WiM/StreamStats/issues/1579. We think it will be good to get feedback or ideas for the cooperators on the most useful way to display the results.

2023-03-30 15:12 UTC, amedenblik approved these changes
I went ahead and updated the services

2023-03-30 16:39 UTC, merged

2023-03-30 16:45 UTC, amedenblik commented
Deployed to https://dev.streamstats.usgs.gov/sc-runoff/