Fixes 1601: POST request to submit batch
USGS-WiM/StreamStats pull request #1645
Opened 2023-06-26 15:50 UTC by alaws-USGS

Closes #1601

2023-06-27 13:31 UTC, harper-wavra reviewed
It's all coming together! 😄 

Is there a zip file with more than 250 points to use for testing? I tried with the one linked in the issue, but it isn't a point shapefile so I get an error. 

Just a couple display comments/ideas
- spinner on the Submit Batch button while the request is being made
- if the request goes though correctly (200) clear out form

2023-06-27 13:54 UTC, alaws-USGS commented
@harper-wavra I downloaded and created a file for testing over 250 points. Short story long, the dataset you referenced has a geometry of type Point Z (elevation) and I modified them to Point. This file works:

[GageLocUpdated.zip](https://github.com/USGS-WiM/StreamStats/files/11882980/GageLocUpdated.zip)

2023-06-27 14:01 UTC, harper-wavra commented
Thanks for that updated file! The 250 points functionally seemed to be working well. 

The only note I had about that is the toast message disappears pretty fast. Maybe we could either up the time that toast message is displayed, or show that message in the modal above the submit batch button?

2023-06-27 14:19 UTC, amedenblik requested changes
Hooray! This is great. I am seeing some errors like you were seeing yesterday (https://code.usgs.gov/StreamStats/web-services-and-apis/ss-batchprocessor/-/issues/68), so we will track those down with the GIS team.

2023-06-27 14:19 UTC, amedenblik commented on src/Views/batchprocessor.html
> +    <div class="bp-submit-success" ng-show="vm.submitBatchSuccessAlert">The batch was submitted successfully. You will be
`submitBatchSuccessAlert` is never set to true, so this message never shows up

2023-06-27 14:19 UTC, amedenblik commented on src/Controllers/BatchProcessorController.ts
> +                    }).finally(() => { this.submittingBatch = false; });
Clear the form after successful submission

2023-06-27 14:19 UTC, amedenblik commented on src/Controllers/BatchProcessorController.ts
> +                    }).finally(() => { this.submittingBatch = false; });
Also refresh the Batch Status tab if an email address has already been entered. How to recreate the "error" (not really an error but may be confusing for users):

1. Go to Batch Status tab
2. Enter email and look at my batches
3. Go to Submit Batch tab
4. Submit a batch
5. Go back to Batch Status tab
6. My new batch isn't showing up yet; I have to click the "Check Status" button again to refresh the list

2023-06-27 14:19 UTC, amedenblik commented on src/Controllers/BatchProcessorController.js
> +                            _this.toaster.pop('error', "The submission failed for the following reason:" + detail, "", 5000);
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/ac175b98-feef-4876-ac9b-3317d71dcd82)

Add space after the colon

```suggestion
                            _this.toaster.pop('error', "The submission failed for the following reason: " + detail, "", 5000);
```

2023-06-27 14:19 UTC, amedenblik commented on src/Views/batchprocessor.html
> +                class="fa fa-share"></i><span>&nbsp;&nbsp;Submit Batch Over 250 Points</span></button>
Turn the fa-share icon into a spinning loader icon while the batch is being submitted, since large batches take a minute to process.

2023-06-28 14:32 UTC, alaws-USGS commented
- [ ] Move 250 point message to modal as div
- [ ] Update trigger for "submissions successful' message div
- [ ] Clear form after batch submitted
- [ ] Update batch status if email entered when batch is submitted
- [ ] Turn icon into spinning wheel while submitting batch

2023-06-28 17:28 UTC, alaws-USGS commented
@amedenblik and @harper-wavra, I added the syntax to use the batch status email to auto populate the batch status tab when a batch is submitted. Check this out when you are reviewing and let me know your thoughts.

2023-06-29 15:25 UTC, amedenblik requested changes
I like the changes, especially how the Batch Status tab is now populated with the email address after submitting a batch! Please see comments

2023-06-29 15:25 UTC, amedenblik commented on src/Views/batchprocessor.html
> +            <i ng-if="vm.submittingBatch == true" class="fa fa-spinner fa-3x fa-spin loadingSpinner"></i>
Can we use this spinner instead? This is what we use for other buttons in the app
```suggestion
            <i ng-if="vm.submittingBatch == true" class="fa fa-refresh fa-spin"></i>

```

2023-06-29 15:25 UTC, amedenblik commented on src/Views/batchprocessor.html
> +            <i ng-if="vm.submittingBatch == true" class="fa fa-spinner fa-3x fa-spin loadingSpinner"></i>
Can we use this spinner instead? This is what we use for other buttons in the app
```suggestion
            <i ng-if="vm.submittingBatch == true" class="fa fa-refresh fa-spin"></i>

```

2023-06-29 15:25 UTC, amedenblik commented on src/Controllers/BatchProcessorController.ts
> +        public submitBatch(submit250:boolean=false): void {
When a batch is submitting, can we have a "wait" toaster appear? We typically show these toasts after submitting requests that take a while:

`this.toaster.pop("wait", "Submitting Batch", "Please wait...", 0);`

Example from when a user delineates a basin:
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/e376a6a6-cf33-480b-9227-8ac1676b62ad)

2023-06-29 16:05 UTC, alaws-USGS commented
Toaster.pop for submitting added!

2023-06-29 16:31 UTC, amedenblik approved these changes

2023-06-29 16:31 UTC, merged

2023-06-29 16:43 UTC, amedenblik commented
https://dev.streamstats.usgs.gov/bp/ has been updated