Fixes 1631: loading spinners
USGS-WiM/StreamStats pull request #1656
Opened 2023-07-03 14:27 UTC by alaws-USGS

Closes #1631

2023-07-05 19:57 UTC, harper-wavra requested changes
The bug seems to be fixed. I think we are just missing the text that says "Please select a State / Region to select Flow Statistics" and "Please select a State / Region to select Basin Characteristics" when a region is not selected.

2023-07-06 18:11 UTC, alaws-USGS commented
@harper-wavra I added the messages and tested that they appear after submitting a batch.

2023-07-06 19:35 UTC, harper-wavra approved these changes

2023-07-06 19:35 UTC, merged

2023-07-06 19:40 UTC, harper-wavra commented
Updated https://dev.streamstats.usgs.gov/bp/.