Fixes #1707 Gageplots Feedback - Annual Peak Streamflow plot
USGS-WiM/StreamStats pull request #1913
Opened 2024-01-23 16:13 UTC by maggiejaenicke

Closes #1707

2024-01-25 20:20 UTC, harper-wavra requested changes
Working well! This was a lot of changes, great job!

- Sometimes the log scale is not an option, [image](https://github.com/USGS-WiM/StreamStats/assets/59063181/f8c4eab8-4e5b-4780-91cf-9a980a3972db). I could not remember if we had talked about this, so maybe this is by design?
- After editing the time period shown on the plot, then clicking 'reset zoom' the page would sometimes freeze for me. This happened the most at gage 1234000. Not sure how easy this will be to fix, so could always make a separate issue.

2024-01-25 20:20 UTC, harper-wavra commented on src/Controllers/GagePageController.ts
> +            headerFormat:'<b>Annual Peak Streamflow</b><br> Plotted on Water Year  HELLOOOOO: <b>' + this.selectedYear,
```suggestion
            headerFormat:'<b>Annual Peak Streamflow</b><br> Plotted on Water Year: <b>' + this.selectedYear,
```

2024-01-25 20:20 UTC, harper-wavra commented on src/Controllers/GagePageController.ts
> +                url = 'https://nwis.waterservices.usgs.gov/nwis/dv/?format=json&sites=' + this.gage.code + '&parameterCd=00060&statCd=00003&startDT=1900-01-01&endDT=2024-01-11';
Should the `endDT` be hard coded here?

2024-01-25 20:27 UTC, maggiejaenicke commented on src/Controllers/GagePageController.ts
> +            headerFormat:'<b>Annual Peak Streamflow</b><br> Plotted on Water Year  HELLOOOOO: <b>' + this.selectedYear,
Lolll

2024-01-26 19:12 UTC, maggiejaenicke commented
> * Sometimes the log scale is not an option, [image](https://github.com/USGS-WiM/StreamStats/assets/59063181/f8c4eab8-4e5b-4780-91cf-9a980a3972db). I could not remember if we had talked about this, so maybe this is by design?

Similar to how the heat map determines if it should use log or linear, the log scale check box is only available if the data values do not contain any negative values (which causes the log option not to work on Highcharts). I have it set to not show the checkbox at all in this case (`ng-if="vm.containsNegatives() === false"`), but maybe it would be better/more self-explanatory if it were grayed out and still visible? 


> * After editing the time period shown on the plot, then clicking 'reset zoom' the page would sometimes freeze for me. This happened the most at gage 1234000. Not sure how easy this will be to fix, so could always make a separate issue.

12340000 seems to be super slow for a lot of things, and I think that is because of the huge data gap in the daily value data. The way that gap works is all the values are looped through so that each day has a data row and days without data get a null value. It does have to loop through a lot of data but I don't really know why it's soooo slow. I added some context about this to [this issue](https://github.com/USGS-WiM/StreamStats/issues/1562), so maybe we can work on address loading issues all at once.

2024-01-31 13:53 UTC, harper-wavra approved these changes
> Maybe it would be better/more self-explanatory if it were grayed out and still visible
I like this idea. 

Other than that, things are looking good to me!

2024-02-01 05:34 UTC, amedenblik requested changes
Awesome job, Maggie! This is looking sharp.

- [x] On gage 03132000, I am not seeing labels for any of the the horizontal streamgage statistics lines:
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/f3092675-7343-44ff-956a-56d510d6d5bc)

- As discussed, it would be nice to improve loading times for gages that are especially slow, but we can address this in other issues.

2024-02-05 22:30 UTC, maggiejaenicke commented
Notes to self: 

> * [ ]  On gage 03132000, I am not seeing labels for any of the the horizontal streamgage statistics lines:

I think I could just set this up in a function similar to `updateShadedStats()` or `updatePeaksAfterZoom()` to update the endpoints of the flood stats lines whenever the axis is resized. Would need this to apply to all of the flood stats, even the ones not currently shown, so that if they are switched in the dropdown, they have the right endpoints.

2024-02-16 06:07 UTC, amedenblik approved these changes

2024-02-16 06:07 UTC, merged

2024-02-16 06:13 UTC, amedenblik commented
Deployed to https://dev.streamstats.usgs.gov/gageplots/