Fixes #1943 - add polyline option for delineation by line
USGS-WiM/StreamStats pull request #1952
Opened 2024-02-12 19:37 UTC by harper-wavra

If wanting to test before https://code.usgs.gov/StreamStats/web-services-and-apis/ss-pourpoint/-/merge_requests/16 is merged and deployed. Will need to run pourpoint branch HW-21 locally and update the pourpointServices to 'http://127.0.0.1:8000' in the appconfig.

2024-02-13 21:13 UTC, amedenblik requested changes
Works well!

2024-02-13 21:13 UTC, amedenblik commented on src/Views/sidebarview.html
> +                            <p ng-show="vm.studyAreaService.zoomLevel15 && vm.studyAreaService.doDelineateFlag && vm.studyAreaService.delineateByLine"><strong>Step 3:</strong> Use your mouse or finge
Is there a way to change the instructions in the map interface as well? It says "Click last point to finish line." which may be confusing.
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/7f2e8338-512b-46c6-ad28-67caca8f710a)

2024-02-13 21:13 UTC, amedenblik commented on src/Controllers/MapController.ts
> +                            console.log(valid)
```suggestion

```

2024-02-13 21:13 UTC, amedenblik commented on src/Controllers/MapController.ts
> +                                console.log(point)
```suggestion

```

2024-02-13 21:13 UTC, amedenblik commented on src/Controllers/MapController.ts
> +                            console.log(points)
```suggestion

```

2024-02-13 21:27 UTC, amedenblik commented
We should redeploy SS-Pourpoint after this is merged, to include https://github.com/USGS-WiM/StreamStats/pull/1952

2024-02-13 21:47 UTC, amedenblik commented on src/Views/sidebarview.html
> +                            <p ng-show="vm.studyAreaService.zoomLevel15 && vm.studyAreaService.doDelineateFlag && vm.studyAreaService.delineateByLine"><strong>Step 3:</strong> Use your mouse or finge
We decided the default instructions are fine but are going to change "polyline" to "line" in the sidebar instructions.

2024-02-13 22:09 UTC, amedenblik approved these changes

2024-02-13 22:09 UTC, merged

2024-02-14 16:06 UTC, harper-wavra commented
Deployed to https://dev.streamstats.usgs.gov/sc-runoff/