Fixes #1921: Stage vs. Discharge Plot - Move Legend for Age & Quality Data
USGS-WiM/StreamStats pull request #1969
Opened 2024-02-26 16:31 UTC by maggiejaenicke

- Moves legend off of stage vs. discharge plot area 
- Overhauls stage vs. discharge plot inputs organization (view layout on a normal plot like `02173500`)
- Adds `ng-if` statements to the legend and the sliders so that if a plot does not have USGS measurements, these items won't appear. `06326510` is a test plot for this -- ignore the other issues this particular plot has for now (they will be rectified in https://github.com/USGS-WiM/StreamStats/issues/1925)

Closes #1921

2024-02-26 19:09 UTC, amedenblik requested changes
This looks great, Maggie! I really like these changes. I made one small comment.

2024-02-26 19:09 UTC, amedenblik commented on src/Views/gagepage.html
> +                            <div class="stagedischarge-inputs-container">
Very small comment-- when there is no data to display for the Stage Vs. Discharge Plot, there is some extra space above the graph:

![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/9f0eda14-93d9-48da-a2b7-3898f2f8b3a8)

Compare to others: almost no blank space here
![image](https://github.com/USGS-WiM/StreamStats/assets/40237491/be2f0307-00e1-4182-b0b5-1434bf244991)

2024-02-26 20:52 UTC, maggiejaenicke commented on src/Views/gagepage.html
> +                            <div class="stagedischarge-inputs-container">
I think it's fixed!

2024-02-27 01:13 UTC, amedenblik approved these changes

2024-02-27 01:13 UTC, merged

2024-02-27 01:29 UTC, amedenblik commented
Deployed to https://dev.streamstats.usgs.gov/gageplots/